name: CI + Docker CI/CD

on:
  push:
    branches:
      - main
      - feat/flask-docker-clean-final
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Create and activate virtual environment
      - name: Create virtual environment
        run: python -m venv venv

      # 4. Install Python dependencies
      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Lint code
      - name: Lint
        run: |
          source venv/bin/activate
          flake8 app

      # 6. Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Login to Docker Hub using secrets
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker image
      - name: Build Docker image
        run: docker build -t arif346/my-app:latest .

      # 5. Push Docker image
      - name: Push Docker image
        run: docker push arif346/my-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

